services:
  - type: web
    name: interview-prep-ai-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
